"""refactor_candidate_profile_to_screening

Revision ID: 3af6a0042c6c
Revises: b887d94c9f35
Create Date: 2025-12-23 12:36:27.631586

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af6a0042c6c'
down_revision: Union[str, None] = 'b887d94c9f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_screenings',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('previous_training', sa.JSON(), nullable=True),
    sa.Column('documents_upload', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_screenings_candidate_id'), 'candidate_screenings', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_screenings_id'), 'candidate_screenings', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_screenings_is_deleted'), 'candidate_screenings', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_candidate_profiles_batch_number'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_candidate_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_is_deleted'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_training_domain'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trained_by_winvinaya', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('training_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('training_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('training_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('willing_for_training', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ready_to_relocate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('interested_training', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dob', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('candidate_profiles_candidate_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_profiles_pkey'))
    )
    op.create_index(op.f('ix_candidate_profiles_training_domain'), 'candidate_profiles', ['training_domain'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_is_deleted'), 'candidate_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_id'), 'candidate_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_candidate_id'), 'candidate_profiles', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_profiles_batch_number'), 'candidate_profiles', ['batch_number'], unique=False)
    op.drop_index(op.f('ix_candidate_screenings_is_deleted'), table_name='candidate_screenings')
    op.drop_index(op.f('ix_candidate_screenings_id'), table_name='candidate_screenings')
    op.drop_index(op.f('ix_candidate_screenings_candidate_id'), table_name='candidate_screenings')
    op.drop_table('candidate_screenings')
    # ### end Alembic commands ###
