"""add_candidate_related_tables_and_uuid

Revision ID: d178cbfb1145
Revises: 0358b9e4e919
Create Date: 2025-12-11 23:10:20.621640

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd178cbfb1145'
down_revision: Union[str, None] = '0358b9e4e919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_counseling',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('skills_observed', sa.JSON(), nullable=True),
    sa.Column('suitable_training', sa.String(length=500), nullable=True),
    sa.Column('counselor_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('counselor_id', sa.Integer(), nullable=True),
    sa.Column('counseling_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_counseling_candidate_id'), 'candidate_counseling', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_counseling_id'), 'candidate_counseling', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_counseling_is_deleted'), 'candidate_counseling', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_counseling_status'), 'candidate_counseling', ['status'], unique=False)
    op.create_table('candidate_documents',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_document_type'), 'candidate_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_candidate_documents_id'), 'candidate_documents', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_is_deleted'), 'candidate_documents', ['is_deleted'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('trained_by_winvinaya', sa.Boolean(), nullable=False),
    sa.Column('training_domain', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('training_from', sa.DateTime(), nullable=True),
    sa.Column('training_to', sa.DateTime(), nullable=True),
    sa.Column('willing_for_training', sa.Boolean(), nullable=False),
    sa.Column('ready_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('interested_training', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_batch_number'), 'candidate_profiles', ['batch_number'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_candidate_id'), 'candidate_profiles', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_profiles_id'), 'candidate_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_is_deleted'), 'candidate_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_training_domain'), 'candidate_profiles', ['training_domain'], unique=False)
    op.add_column('candidates', sa.Column('public_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_candidates_public_id'), 'candidates', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_public_id'), table_name='candidates')
    op.drop_column('candidates', 'public_id')
    op.drop_index(op.f('ix_candidate_profiles_training_domain'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_is_deleted'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_candidate_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_batch_number'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_candidate_documents_is_deleted'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_document_type'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_candidate_counseling_status'), table_name='candidate_counseling')
    op.drop_index(op.f('ix_candidate_counseling_is_deleted'), table_name='candidate_counseling')
    op.drop_index(op.f('ix_candidate_counseling_id'), table_name='candidate_counseling')
    op.drop_index(op.f('ix_candidate_counseling_candidate_id'), table_name='candidate_counseling')
    op.drop_table('candidate_counseling')
    # ### end Alembic commands ###
