"""refactor_candidate_counseling_fields

Revision ID: 753f08222c79
Revises: 3af6a0042c6c
Create Date: 2025-12-24 00:13:12.934887

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '753f08222c79'
down_revision: Union[str, None] = '3af6a0042c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_counseling', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('candidate_counseling', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('candidate_counseling', sa.Column('questions', sa.JSON(), nullable=True))
    op.add_column('candidate_counseling', sa.Column('others', sa.JSON(), nullable=True))
    op.add_column('candidate_counseling', sa.Column('counselor_name', sa.String(length=100), nullable=True))
    op.drop_column('candidate_counseling', 'skills_observed')
    op.drop_column('candidate_counseling', 'suitable_training')
    op.drop_column('candidate_counseling', 'counselor_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_counseling', sa.Column('counselor_comments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('candidate_counseling', sa.Column('suitable_training', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('candidate_counseling', sa.Column('skills_observed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('candidate_counseling', 'counselor_name')
    op.drop_column('candidate_counseling', 'others')
    op.drop_column('candidate_counseling', 'questions')
    op.drop_column('candidate_counseling', 'feedback')
    op.drop_column('candidate_counseling', 'skills')
    # ### end Alembic commands ###
