"""add_dob_to_candidate

Revision ID: 38eef25eb495
Revises: 567a22e84135
Create Date: 2025-12-22 22:17:55.438585

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38eef25eb495'
down_revision: Union[str, None] = '567a22e84135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'dob')
    # ### end Alembic commands ###
