"""rename_date_of_birth_to_dob_in_candidate_profiles

Revision ID: b887d94c9f35
Revises: 38eef25eb495
Create Date: 2025-12-22 22:25:37.391914

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b887d94c9f35'
down_revision: Union[str, None] = '38eef25eb495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('dob', sa.DateTime(), nullable=True))
    op.drop_column('candidate_profiles', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('candidate_profiles', 'dob')
    # ### end Alembic commands ###
