"""Add training batch and candidate allocation tables

Revision ID: a6cafaa047ad
Revises: 753f08222c79
Create Date: 2025-12-25 16:21:05.334423

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cafaa047ad'
down_revision: Union[str, None] = '753f08222c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_batches',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('courses', sa.JSON(), nullable=True),
    sa.Column('duration', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('other', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_batches_batch_name'), 'training_batches', ['batch_name'], unique=False)
    op.create_index(op.f('ix_training_batches_id'), 'training_batches', ['id'], unique=False)
    op.create_index(op.f('ix_training_batches_is_deleted'), 'training_batches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_training_batches_public_id'), 'training_batches', ['public_id'], unique=True)
    op.create_index(op.f('ix_training_batches_status'), 'training_batches', ['status'], unique=False)
    op.create_table('candidate_allocations',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_allocations_batch_id'), 'candidate_allocations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_candidate_allocations_candidate_id'), 'candidate_allocations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_allocations_id'), 'candidate_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_allocations_is_deleted'), 'candidate_allocations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_allocations_public_id'), 'candidate_allocations', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_allocations_public_id'), table_name='candidate_allocations')
    op.drop_index(op.f('ix_candidate_allocations_is_deleted'), table_name='candidate_allocations')
    op.drop_index(op.f('ix_candidate_allocations_id'), table_name='candidate_allocations')
    op.drop_index(op.f('ix_candidate_allocations_candidate_id'), table_name='candidate_allocations')
    op.drop_index(op.f('ix_candidate_allocations_batch_id'), table_name='candidate_allocations')
    op.drop_table('candidate_allocations')
    op.drop_index(op.f('ix_training_batches_status'), table_name='training_batches')
    op.drop_index(op.f('ix_training_batches_public_id'), table_name='training_batches')
    op.drop_index(op.f('ix_training_batches_is_deleted'), table_name='training_batches')
    op.drop_index(op.f('ix_training_batches_id'), table_name='training_batches')
    op.drop_index(op.f('ix_training_batches_batch_name'), table_name='training_batches')
    op.drop_table('training_batches')
    # ### end Alembic commands ###
