"""modify_candidate_table_json_fields

Revision ID: 567a22e84135
Revises: d178cbfb1145
Create Date: 2025-12-22 21:57:21.171582

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '567a22e84135'
down_revision: Union[str, None] = 'd178cbfb1145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('guardian_details', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('work_experience', sa.JSON(), nullable=True))
    op.drop_column('candidates', 'currently_employed')
    op.drop_column('candidates', 'parent_name')
    op.drop_column('candidates', 'is_experienced')
    op.drop_column('candidates', 'parent_phone')
    op.drop_column('candidates', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('parent_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('is_experienced', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('parent_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('currently_employed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('candidates', 'work_experience')
    op.drop_column('candidates', 'guardian_details')
    # ### end Alembic commands ###
