"""add_training_extension_tables

Revision ID: d4617ead414c
Revises: 136e271894ea
Create Date: 2026-01-07 15:34:45.850628

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4617ead414c'
down_revision: Union[str, None] = '136e271894ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_assessments',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('assessment_name', sa.String(length=255), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_assessments_batch_id'), 'training_assessments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_training_assessments_candidate_id'), 'training_assessments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_training_assessments_id'), 'training_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_training_assessments_is_deleted'), 'training_assessments', ['is_deleted'], unique=False)
    op.create_table('training_attendance',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_attendance_batch_id'), 'training_attendance', ['batch_id'], unique=False)
    op.create_index(op.f('ix_training_attendance_candidate_id'), 'training_attendance', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_training_attendance_date'), 'training_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_training_attendance_id'), 'training_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_training_attendance_is_deleted'), 'training_attendance', ['is_deleted'], unique=False)
    op.create_table('training_mock_interviews',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_name', sa.String(length=100), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_mock_interviews_batch_id'), 'training_mock_interviews', ['batch_id'], unique=False)
    op.create_index(op.f('ix_training_mock_interviews_candidate_id'), 'training_mock_interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_training_mock_interviews_id'), 'training_mock_interviews', ['id'], unique=False)
    op.create_index(op.f('ix_training_mock_interviews_is_deleted'), 'training_mock_interviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_training_mock_interviews_status'), 'training_mock_interviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_mock_interviews_status'), table_name='training_mock_interviews')
    op.drop_index(op.f('ix_training_mock_interviews_is_deleted'), table_name='training_mock_interviews')
    op.drop_index(op.f('ix_training_mock_interviews_id'), table_name='training_mock_interviews')
    op.drop_index(op.f('ix_training_mock_interviews_candidate_id'), table_name='training_mock_interviews')
    op.drop_index(op.f('ix_training_mock_interviews_batch_id'), table_name='training_mock_interviews')
    op.drop_table('training_mock_interviews')
    op.drop_index(op.f('ix_training_attendance_is_deleted'), table_name='training_attendance')
    op.drop_index(op.f('ix_training_attendance_id'), table_name='training_attendance')
    op.drop_index(op.f('ix_training_attendance_date'), table_name='training_attendance')
    op.drop_index(op.f('ix_training_attendance_candidate_id'), table_name='training_attendance')
    op.drop_index(op.f('ix_training_attendance_batch_id'), table_name='training_attendance')
    op.drop_table('training_attendance')
    op.drop_index(op.f('ix_training_assessments_is_deleted'), table_name='training_assessments')
    op.drop_index(op.f('ix_training_assessments_id'), table_name='training_assessments')
    op.drop_index(op.f('ix_training_assessments_candidate_id'), table_name='training_assessments')
    op.drop_index(op.f('ix_training_assessments_batch_id'), table_name='training_assessments')
    op.drop_table('training_assessments')
    # ### end Alembic commands ###
