"""add_placement_mapping

Revision ID: 42bd88790f09
Revises: b513242f2f73
Create Date: 2026-03-28 15:54:50.966829

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bd88790f09'
down_revision: Union[str, None] = 'b513242f2f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_mappings',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=False),
    sa.Column('mapped_by_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True, comment='Calculated match score at the time of mapping'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Reasoning or notes for the mapping'),
    sa.Column('mapped_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapped_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_role_id', name='uq_candidate_job_role_mapping')
    )
    op.create_index(op.f('ix_placement_mappings_candidate_id'), 'placement_mappings', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_placement_mappings_id'), 'placement_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_placement_mappings_is_deleted'), 'placement_mappings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_mappings_job_role_id'), 'placement_mappings', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_placement_mappings_mapped_by_id'), 'placement_mappings', ['mapped_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_mappings_mapped_by_id'), table_name='placement_mappings')
    op.drop_index(op.f('ix_placement_mappings_job_role_id'), table_name='placement_mappings')
    op.drop_index(op.f('ix_placement_mappings_is_deleted'), table_name='placement_mappings')
    op.drop_index(op.f('ix_placement_mappings_id'), table_name='placement_mappings')
    op.drop_index(op.f('ix_placement_mappings_candidate_id'), table_name='placement_mappings')
    op.drop_table('placement_mappings')
    # ### end Alembic commands ###
