"""Add JobRole model

Revision ID: 3af887c65ae3
Revises: 3c93c33a03ca
Create Date: 2026-03-28 09:37:17.111501

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af887c65ae3'
down_revision: Union[str, None] = '3c93c33a03ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_roles',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'closed', name='jobrolestatus'), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('no_of_vacancies', sa.Integer(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True, comment='{"cities": [], "state": "", "country": ""}'),
    sa.Column('salary_range', sa.JSON(), nullable=True, comment='{"min": float, "max": float, "currency": "INR"}'),
    sa.Column('experience', sa.JSON(), nullable=True, comment='{"min": float, "max": float}'),
    sa.Column('requirements', sa.JSON(), nullable=True, comment='{"skills": [], "qualifications": []}'),
    sa.Column('job_details', sa.JSON(), nullable=True, comment='{"designation": "", "workplace_type": "", "job_type": ""}'),
    sa.Column('other', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_roles_company_id'), 'job_roles', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_roles_contact_id'), 'job_roles', ['contact_id'], unique=False)
    op.create_index(op.f('ix_job_roles_created_by_id'), 'job_roles', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_job_roles_id'), 'job_roles', ['id'], unique=False)
    op.create_index(op.f('ix_job_roles_is_deleted'), 'job_roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_job_roles_public_id'), 'job_roles', ['public_id'], unique=True)
    op.create_index(op.f('ix_job_roles_status'), 'job_roles', ['status'], unique=False)
    op.create_index(op.f('ix_job_roles_title'), 'job_roles', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_roles_title'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_status'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_public_id'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_is_deleted'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_id'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_created_by_id'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_contact_id'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_company_id'), table_name='job_roles')
    op.drop_table('job_roles')
    # ### end Alembic commands ###
