"""add_candidate_assignment_table

Revision ID: 7d562a410c63
Revises: 2239438d062d
Create Date: 2026-03-21 07:55:04.513329

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d562a410c63'
down_revision: Union[str, None] = '2239438d062d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_assignments',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='The sourcing user assigned to the candidate'),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False, comment='The manager/admin who performed the assignment'),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_assignments_assigned_by_id'), 'candidate_assignments', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_candidate_id'), 'candidate_assignments', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_assignments_id'), 'candidate_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_is_deleted'), 'candidate_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_user_id'), 'candidate_assignments', ['user_id'], unique=False)
    op.drop_index('ix_candidate_screening_assignments_assigned_to_id', table_name='candidate_screening_assignments')
    op.drop_index('ix_candidate_screening_assignments_candidate_id', table_name='candidate_screening_assignments')
    op.drop_index('ix_candidate_screening_assignments_id', table_name='candidate_screening_assignments')
    op.drop_index('ix_candidate_screening_assignments_is_deleted', table_name='candidate_screening_assignments')
    op.drop_table('candidate_screening_assignments')
    op.alter_column('dsr_activities', 'total_actual_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsr_activities', 'total_actual_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.create_table('candidate_screening_assignments',
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name='candidate_screening_assignments_assigned_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name='candidate_screening_assignments_assigned_to_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='candidate_screening_assignments_candidate_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='candidate_screening_assignments_pkey')
    )
    op.create_index('ix_candidate_screening_assignments_is_deleted', 'candidate_screening_assignments', ['is_deleted'], unique=False)
    op.create_index('ix_candidate_screening_assignments_id', 'candidate_screening_assignments', ['id'], unique=False)
    op.create_index('ix_candidate_screening_assignments_candidate_id', 'candidate_screening_assignments', ['candidate_id'], unique=True)
    op.create_index('ix_candidate_screening_assignments_assigned_to_id', 'candidate_screening_assignments', ['assigned_to_id'], unique=False)
    op.drop_index(op.f('ix_candidate_assignments_user_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_is_deleted'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_candidate_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_assigned_by_id'), table_name='candidate_assignments')
    op.drop_table('candidate_assignments')
    # ### end Alembic commands ###
