"""add_candidate_pool_table

Revision ID: 7c80119ce570
Revises: b0d5f17bf7f1
Create Date: 2026-04-24 22:16:12.016585

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c80119ce570'
down_revision: Union[str, None] = 'b0d5f17bf7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use raw SQL to safely drop the table if it exists. 
    # In PostgreSQL, dropping the table also automatically drops its associated indexes.
    op.execute("DROP TABLE IF EXISTS candidate_pool CASCADE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_pool',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('disability_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('disability_sub_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('qualification', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('college_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('passing_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('current_ctc', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_donor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_converted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('crm_candidate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crm_candidate_id'], ['candidates.id'], name='candidate_pool_crm_candidate_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='candidate_pool_pkey')
    )
    op.create_index('ix_candidate_pool_state', 'candidate_pool', ['state'], unique=False)
    op.create_index('ix_candidate_pool_source_donor', 'candidate_pool', ['source_donor'], unique=False)
    op.create_index('ix_candidate_pool_qualification', 'candidate_pool', ['qualification'], unique=False)
    op.create_index('ix_candidate_pool_phone', 'candidate_pool', ['phone'], unique=False)
    op.create_index('ix_candidate_pool_name', 'candidate_pool', ['name'], unique=False)
    op.create_index('ix_candidate_pool_is_deleted', 'candidate_pool', ['is_deleted'], unique=False)
    op.create_index('ix_candidate_pool_id', 'candidate_pool', ['id'], unique=False)
    op.create_index('ix_candidate_pool_email', 'candidate_pool', ['email'], unique=False)
    op.create_index('ix_candidate_pool_disability_category', 'candidate_pool', ['disability_category'], unique=False)
    op.create_index('ix_candidate_pool_city', 'candidate_pool', ['city'], unique=False)
    op.create_index('ix_candidate_pool_batch_year', 'candidate_pool', ['batch_year'], unique=False)
    # ### end Alembic commands ###
