"""add_other_column_to_candidate

Revision ID: a6706489793f
Revises: 62518262b7bb
Create Date: 2026-05-15 10:00:00.664219

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6706489793f'
down_revision: Union[str, None] = '62518262b7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_pool_email', table_name='candidate_pool')
    op.drop_index('ix_candidate_pool_id', table_name='candidate_pool')
    op.drop_index('ix_candidate_pool_is_deleted', table_name='candidate_pool')
    op.drop_index('ix_candidate_pool_name', table_name='candidate_pool')
    op.drop_table('candidate_pool')
    op.add_column('candidates', sa.Column('other', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'other')
    op.create_table('candidate_pool',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('disability_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('disability_sub_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('education', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('placement_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status_of_beneficiary', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('donor', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('batch_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('others', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='candidate_pool_pkey')
    )
    op.create_index('ix_candidate_pool_name', 'candidate_pool', ['name'], unique=False)
    op.create_index('ix_candidate_pool_is_deleted', 'candidate_pool', ['is_deleted'], unique=False)
    op.create_index('ix_candidate_pool_id', 'candidate_pool', ['id'], unique=False)
    op.create_index('ix_candidate_pool_email', 'candidate_pool', ['email'], unique=False)
    # ### end Alembic commands ###
