"""Add chat_session_id to AITaskLog

Revision ID: ea1dab589341
Revises: cf133f15dbd2
Create Date: 2026-04-11 17:43:26.429401

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1dab589341'
down_revision: Union[str, None] = 'cf133f15dbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_task_logs', sa.Column('chat_session_id', sa.Integer(), nullable=True, comment='Chat session from which this task was spawned'))
    op.create_index(op.f('ix_ai_task_logs_chat_session_id'), 'ai_task_logs', ['chat_session_id'], unique=False)
    op.create_foreign_key(None, 'ai_task_logs', 'ai_chat_sessions', ['chat_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_task_logs', type_='foreignkey')
    op.drop_index(op.f('ix_ai_task_logs_chat_session_id'), table_name='ai_task_logs')
    op.drop_column('ai_task_logs', 'chat_session_id')
    # ### end Alembic commands ###
