"""multi_course_assessment_support

Revision ID: 44e461eebbb1
Revises: ce0a1441230d
Create Date: 2026-01-10 15:18:43.365904

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e461eebbb1'
down_revision: Union[str, None] = 'ce0a1441230d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_assessments', sa.Column('course_marks', sa.JSON(), nullable=True))
    op.alter_column('training_assessments', 'course_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="json_build_array(course_name)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_assessments', 'course_name',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('training_assessments', 'course_marks')
    # ### end Alembic commands ###
