"""create training batch events table

Revision ID: 88455daeea6f
Revises: 8b5a1d57ffb5
Create Date: 2026-01-09 16:04:53.290329

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88455daeea6f'
down_revision: Union[str, None] = '8b5a1d57ffb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_batch_events',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_batch_events_batch_id'), 'training_batch_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_training_batch_events_date'), 'training_batch_events', ['date'], unique=False)
    op.create_index(op.f('ix_training_batch_events_id'), 'training_batch_events', ['id'], unique=False)
    op.create_index(op.f('ix_training_batch_events_is_deleted'), 'training_batch_events', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_batch_events_is_deleted'), table_name='training_batch_events')
    op.drop_index(op.f('ix_training_batch_events_id'), table_name='training_batch_events')
    op.drop_index(op.f('ix_training_batch_events_date'), table_name='training_batch_events')
    op.drop_index(op.f('ix_training_batch_events_batch_id'), table_name='training_batch_events')
    op.drop_table('training_batch_events')
    # ### end Alembic commands ###
