"""add_dynamic_fields_table

Revision ID: 8a6ece19073b
Revises: a6cafaa047ad
Create Date: 2026-01-01 23:01:02.964060

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6ece19073b'
down_revision: Union[str, None] = 'a6cafaa047ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_fields',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_fields_entity_type'), 'dynamic_fields', ['entity_type'], unique=False)
    op.create_index(op.f('ix_dynamic_fields_id'), 'dynamic_fields', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_fields_is_deleted'), 'dynamic_fields', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_fields_is_deleted'), table_name='dynamic_fields')
    op.drop_index(op.f('ix_dynamic_fields_id'), table_name='dynamic_fields')
    op.drop_index(op.f('ix_dynamic_fields_entity_type'), table_name='dynamic_fields')
    op.drop_table('dynamic_fields')
    # ### end Alembic commands ###
