"""add assigned_to to dsr_activities

Revision ID: 6d14b47db469
Revises: 6c0a00577ecc
Create Date: 2026-03-07 21:16:57.582786

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d14b47db469'
down_revision: Union[str, None] = '6c0a00577ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '134885e270b6'


def upgrade() -> None:
    # Check if column exists
    conn = op.get_bind()
    res = conn.execute(sa.text(
        "SELECT count(*) FROM information_schema.columns "
        "WHERE table_name='dsr_activities' AND column_name='assigned_to'"
    ))
    column_exists = res.scalar() > 0

    if not column_exists:
        op.add_column('dsr_activities', sa.Column('assigned_to', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_dsr_activities_assigned_to'), 'dsr_activities', ['assigned_to'], unique=False)
        op.create_foreign_key(None, 'dsr_activities', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dsr_activities', type_='foreignkey')
    op.drop_index(op.f('ix_dsr_activities_assigned_to'), table_name='dsr_activities')
    op.drop_column('dsr_activities', 'assigned_to')
    # ### end Alembic commands ###
