"""Add training batch extension history

Revision ID: bdb2a669bad2
Revises: f580dca92b5d
Create Date: 2026-01-08 21:16:08.471420

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb2a669bad2'
down_revision: Union[str, None] = 'f580dca92b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_batch_extensions',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('previous_close_date', sa.Date(), nullable=False),
    sa.Column('new_close_date', sa.Date(), nullable=False),
    sa.Column('extension_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_batch_extensions_id'), 'training_batch_extensions', ['id'], unique=False)
    op.create_index(op.f('ix_training_batch_extensions_is_deleted'), 'training_batch_extensions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_training_batch_extensions_public_id'), 'training_batch_extensions', ['public_id'], unique=True)
    op.alter_column('training_batches', 'total_extension_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_batches', 'total_extension_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_training_batch_extensions_public_id'), table_name='training_batch_extensions')
    op.drop_index(op.f('ix_training_batch_extensions_is_deleted'), table_name='training_batch_extensions')
    op.drop_index(op.f('ix_training_batch_extensions_id'), table_name='training_batch_extensions')
    op.drop_table('training_batch_extensions')
    # ### end Alembic commands ###
