"""add_interview_category_to_mock_interview

Revision ID: 220f22fca038
Revises: d4dab2ba591d
Create Date: 2026-05-06 12:59:28.106754

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220f22fca038'
down_revision: Union[str, None] = 'd4dab2ba591d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_mock_interviews', sa.Column('interview_category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_mock_interviews', 'interview_category')
    # ### end Alembic commands ###
