"""add_ai_task_log_table

Revision ID: b5e77475fa20
Revises: 7e9a1b2c3d4f
Create Date: 2026-04-11 16:34:28.946694

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5e77475fa20'
down_revision: Union[str, None] = '7e9a1b2c3d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_task_logs',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False, comment="Human-readable task name, e.g. 'Process WhatsApp Enquiry'"),
    sa.Column('trigger', sa.Enum('manual', 'webhook', 'schedule', 'api', 'system', name='aitasktrigger'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'planning', 'running', 'awaiting_approval', 'completed', 'partially_completed', 'failed', 'cancelled', name='aitaskstatus'), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True, comment='User who triggered this task (null for automated/webhook triggers)'),
    sa.Column('ai_provider', sa.String(length=50), nullable=True, comment='LLM provider used: gemini, openai, ollama'),
    sa.Column('ai_model', sa.String(length=100), nullable=True, comment='Exact model name used, e.g. gemini-1.5-flash'),
    sa.Column('raw_input', sa.JSON(), nullable=True, comment='The original trigger input payload (e.g., WhatsApp message data)'),
    sa.Column('context_snapshot', sa.JSON(), nullable=True, comment='DB context loaded before planning (e.g., existing contact record)'),
    sa.Column('plan', sa.JSON(), nullable=True, comment='Ordered list of tool calls the LLM planned to make'),
    sa.Column('plan_reasoning', sa.Text(), nullable=True, comment="LLM's chain-of-thought reasoning for this plan"),
    sa.Column('steps', sa.JSON(), nullable=True, comment='Ordered list of ToolStepLog dicts capturing every tool call result'),
    sa.Column('tools_called', sa.Integer(), nullable=False, comment='Total number of tool calls made in this run'),
    sa.Column('tools_succeeded', sa.Integer(), nullable=False),
    sa.Column('tools_failed', sa.Integer(), nullable=False),
    sa.Column('records_affected', sa.Integer(), nullable=False, comment='Total DB records created/updated across all tool calls'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='True if this task was paused pending human approval'),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True, comment='User who approved this task (if approval was required)'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated human-readable summary of what was accomplished'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Top-level error if the task failed entirely'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Total wall-clock time in milliseconds'),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True, comment='Estimated LLM cost in USD for this task run'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_task_logs_id'), 'ai_task_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_task_logs_is_deleted'), 'ai_task_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_task_logs_public_id'), 'ai_task_logs', ['public_id'], unique=True)
    op.create_index(op.f('ix_ai_task_logs_status'), 'ai_task_logs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_task_logs_task_name'), 'ai_task_logs', ['task_name'], unique=False)
    op.create_index(op.f('ix_ai_task_logs_trigger'), 'ai_task_logs', ['trigger'], unique=False)
    op.create_index(op.f('ix_ai_task_logs_triggered_by_user_id'), 'ai_task_logs', ['triggered_by_user_id'], unique=False)
    op.drop_index('ix_whatsapp_messages_from_phone', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_id', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_is_deleted', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_processing_status', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_wa_message_id', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_wa_phone_number_id', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wa_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="Meta's unique message ID (wamid.*) — used for idempotency"),
    sa.Column('wa_phone_number_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Meta Phone Number ID that received the message'),
    sa.Column('from_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment="Sender's phone number in E.164 format e.g. 919876543210"),
    sa.Column('from_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='WhatsApp display name of the sender'),
    sa.Column('message_body', sa.TEXT(), autoincrement=False, nullable=True, comment='Raw text content of the message'),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Meta message type: text | image | document | audio | video | sticker | location'),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment="Timestamp from Meta's webhook payload"),
    sa.Column('processing_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Current processing state of this message'),
    sa.Column('ai_intent', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='AI-classified intent: new_person | known_contact | follow_up | ignore'),
    sa.Column('ai_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='AI classification confidence score 0.0 – 1.0'),
    sa.Column('crm_action_taken', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Summary of CRM records created/updated: {lead_id, contact_id, company_id, task_id, activity_id}'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Error details if processing_status is failed'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='whatsapp_messages_pkey')
    )
    op.create_index('ix_whatsapp_messages_wa_phone_number_id', 'whatsapp_messages', ['wa_phone_number_id'], unique=False)
    op.create_index('ix_whatsapp_messages_wa_message_id', 'whatsapp_messages', ['wa_message_id'], unique=True)
    op.create_index('ix_whatsapp_messages_processing_status', 'whatsapp_messages', ['processing_status'], unique=False)
    op.create_index('ix_whatsapp_messages_is_deleted', 'whatsapp_messages', ['is_deleted'], unique=False)
    op.create_index('ix_whatsapp_messages_id', 'whatsapp_messages', ['id'], unique=False)
    op.create_index('ix_whatsapp_messages_from_phone', 'whatsapp_messages', ['from_phone'], unique=False)
    op.drop_index(op.f('ix_ai_task_logs_triggered_by_user_id'), table_name='ai_task_logs')
    op.drop_index(op.f('ix_ai_task_logs_trigger'), table_name='ai_task_logs')
    op.drop_index(op.f('ix_ai_task_logs_task_name'), table_name='ai_task_logs')
    op.drop_index(op.f('ix_ai_task_logs_status'), table_name='ai_task_logs')
    op.drop_index(op.f('ix_ai_task_logs_public_id'), table_name='ai_task_logs')
    op.drop_index(op.f('ix_ai_task_logs_is_deleted'), table_name='ai_task_logs')
    op.drop_index(op.f('ix_ai_task_logs_id'), table_name='ai_task_logs')
    op.drop_table('ai_task_logs')
    # ### end Alembic commands ###
