"""add_review_fields_to_dsr_entries

Revision ID: 0a5ef1dfc7c8
Revises: 7063d510cef2
Create Date: 2026-03-07 23:09:36.193594

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5ef1dfc7c8'
down_revision: Union[str, None] = '7063d510cef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsr_entries', sa.Column('admin_notes', sa.Text(), nullable=True, comment='Admin feedback on approve / rejection'))
    op.add_column('dsr_entries', sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='Admin who approved or rejected this entry'))
    op.add_column('dsr_entries', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when admin reviewed'))
    op.create_foreign_key(None, 'dsr_entries', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dsr_entries', type_='foreignkey')
    op.drop_column('dsr_entries', 'reviewed_at')
    op.drop_column('dsr_entries', 'reviewed_by')
    op.drop_column('dsr_entries', 'admin_notes')
    # ### end Alembic commands ###
