"""add_company_holidays_table

Revision ID: 941bbd119c38
Revises: 5fa312cb22cf
Create Date: 2026-03-18 07:47:37.935773

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941bbd119c38'
down_revision: Union[str, None] = '5fa312cb22cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_holidays',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_holidays_holiday_date'), 'company_holidays', ['holiday_date'], unique=True)
    op.create_index(op.f('ix_company_holidays_holiday_name'), 'company_holidays', ['holiday_name'], unique=False)
    op.create_index(op.f('ix_company_holidays_id'), 'company_holidays', ['id'], unique=False)
    op.create_index(op.f('ix_company_holidays_is_deleted'), 'company_holidays', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_company_holidays_public_id'), 'company_holidays', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_holidays_public_id'), table_name='company_holidays')
    op.drop_index(op.f('ix_company_holidays_is_deleted'), table_name='company_holidays')
    op.drop_index(op.f('ix_company_holidays_id'), table_name='company_holidays')
    op.drop_index(op.f('ix_company_holidays_holiday_name'), table_name='company_holidays')
    op.drop_index(op.f('ix_company_holidays_holiday_date'), table_name='company_holidays')
    op.drop_table('company_holidays')
    # ### end Alembic commands ###
