"""add assigned_to to dsr_activities

Revision ID: 6d14b47db469
Revises: 6c0a00577ecc
Create Date: 2026-03-07 21:16:57.582786

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d14b47db469'
down_revision: Union[str, None] = '6c0a00577ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    table_to_drop = 'candidate_screening_assignments'
    if table_to_drop in tables:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_to_drop)]
        for idx in ['ix_candidate_screening_assignments_assigned_to_id', 
                    'ix_candidate_screening_assignments_candidate_id', 
                    'ix_candidate_screening_assignments_id', 
                    'ix_candidate_screening_assignments_is_deleted']:
            if idx in indexes:
                op.drop_index(idx, table_name=table_to_drop)
        op.drop_table(table_to_drop)
    op.add_column('dsr_activities', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dsr_activities_assigned_to'), 'dsr_activities', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'dsr_activities', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dsr_activities', type_='foreignkey')
    op.drop_index(op.f('ix_dsr_activities_assigned_to'), table_name='dsr_activities')
    op.drop_column('dsr_activities', 'assigned_to')
    op.create_table('candidate_screening_assignments',
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name='candidate_screening_assignments_assigned_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name='candidate_screening_assignments_assigned_to_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='candidate_screening_assignments_candidate_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='candidate_screening_assignments_pkey')
    )
    op.create_index('ix_candidate_screening_assignments_is_deleted', 'candidate_screening_assignments', ['is_deleted'], unique=False)
    op.create_index('ix_candidate_screening_assignments_id', 'candidate_screening_assignments', ['id'], unique=False)
    op.create_index('ix_candidate_screening_assignments_candidate_id', 'candidate_screening_assignments', ['candidate_id'], unique=True)
    op.create_index('ix_candidate_screening_assignments_assigned_to_id', 'candidate_screening_assignments', ['assigned_to_id'], unique=False)
    # ### end Alembic commands ###
