"""add_activity_effort_tracking

Revision ID: 487f979ccfdd
Revises: 941bbd119c38
Create Date: 2026-03-18 12:44:44.359009

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487f979ccfdd'
down_revision: Union[str, None] = '941bbd119c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsr_activities', sa.Column('actual_start_date', sa.Date(), nullable=True))
    op.add_column('dsr_activities', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('dsr_activities', sa.Column('total_actual_hours', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dsr_activities', 'total_actual_hours')
    op.drop_column('dsr_activities', 'estimated_hours')
    op.drop_column('dsr_activities', 'actual_start_date')
    # ### end Alembic commands ###
