"""Add actual_end_date to dsr_activities

Revision ID: f82b6ac29d1d
Revises: 35a7753cb3e7
Create Date: 2026-03-04 10:47:48.048661

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82b6ac29d1d'
down_revision: Union[str, None] = '35a7753cb3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsr_activities', sa.Column('actual_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dsr_activities', 'actual_end_date')
    # ### end Alembic commands ###
