"""update training batch disability_types to JSON

Revision ID: 1f9a0629b648
Revises: d9a3c1e8e177
Create Date: 2026-02-09 10:41:40.329344

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9a0629b648'
down_revision: Union[str, None] = 'd9a3c1e8e177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add disability_types column
    op.add_column('training_batches', sa.Column('disability_types', sa.JSON(), nullable=True))
    
    # Migrate data: convert single string to JSON array
    # Note: Using sa.text for raw SQL execution
    op.execute("UPDATE training_batches SET disability_types = json_build_array(disability_type) WHERE disability_type IS NOT NULL")
    
    # Drop old column
    op.drop_column('training_batches', 'disability_type')
    
    # Drop email templates and triggers if they were removed from models
    op.drop_index('ix_email_report_triggers_id', table_name='email_report_triggers')
    op.drop_index('ix_email_report_triggers_is_deleted', table_name='email_report_triggers')
    op.drop_table('email_report_triggers')
    op.drop_index('ix_email_templates_id', table_name='email_templates')
    op.drop_index('ix_email_templates_is_deleted', table_name='email_templates')
    op.drop_index('ix_email_templates_name', table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_batches', sa.Column('disability_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('training_batches', 'disability_types')
    op.create_table('email_report_triggers',
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('recipients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('schedule', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], name='email_report_triggers_template_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_report_triggers_pkey')
    )
    op.create_index('ix_email_report_triggers_is_deleted', 'email_report_triggers', ['is_deleted'], unique=False)
    op.create_index('ix_email_report_triggers_id', 'email_report_triggers', ['id'], unique=False)
    op.create_table('email_templates',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='email_templates_pkey')
    )
    op.create_index('ix_email_templates_name', 'email_templates', ['name'], unique=True)
    op.create_index('ix_email_templates_is_deleted', 'email_templates', ['is_deleted'], unique=False)
    op.create_index('ix_email_templates_id', 'email_templates', ['id'], unique=False)
    # ### end Alembic commands ###
