"""Add SWOT opportunities and threats columns to training candidate analysis

Revision ID: e696de986661
Revises: a3f9c2e1b8d4
Create Date: 2026-06-01 11:40:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e696de986661'
down_revision: Union[str, None] = 'a3f9c2e1b8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_candidate_analysis', sa.Column('opportunities', sa.Text(), nullable=True))
    op.add_column('training_candidate_analysis', sa.Column('threats', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_candidate_analysis', 'threats')
    op.drop_column('training_candidate_analysis', 'opportunities')
    # ### end Alembic commands ###
