"""add workexperience to candidate_counseling

Revision ID: 17c2f1c4f8ea
Revises: 6162ecedebcb
Create Date: 2026-01-20 17:10:04.927771

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c2f1c4f8ea'
down_revision: Union[str, None] = '6162ecedebcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_counseling', sa.Column('workexperience', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_counseling', 'workexperience')
    # ### end Alembic commands ###
