"""add_dsr_leave_applications_table

Revision ID: d036b2b280fd
Revises: 2a674dc59b03
Create Date: 2026-03-11 23:08:27.553435

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd036b2b280fd'
down_revision: Union[str, None] = '2a674dc59b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsr_leave_applications',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='dsrleavestatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_leave_applications_end_date'), 'dsr_leave_applications', ['end_date'], unique=False)
    op.create_index(op.f('ix_dsr_leave_applications_id'), 'dsr_leave_applications', ['id'], unique=False)
    op.create_index(op.f('ix_dsr_leave_applications_is_deleted'), 'dsr_leave_applications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dsr_leave_applications_leave_type'), 'dsr_leave_applications', ['leave_type'], unique=False)
    op.create_index(op.f('ix_dsr_leave_applications_public_id'), 'dsr_leave_applications', ['public_id'], unique=True)
    op.create_index(op.f('ix_dsr_leave_applications_start_date'), 'dsr_leave_applications', ['start_date'], unique=False)
    op.create_index(op.f('ix_dsr_leave_applications_status'), 'dsr_leave_applications', ['status'], unique=False)
    op.create_index(op.f('ix_dsr_leave_applications_user_id'), 'dsr_leave_applications', ['user_id'], unique=False)
    op.alter_column('dsr_entries', 'is_leave',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsr_entries', 'is_leave',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_dsr_leave_applications_user_id'), table_name='dsr_leave_applications')
    op.drop_index(op.f('ix_dsr_leave_applications_status'), table_name='dsr_leave_applications')
    op.drop_index(op.f('ix_dsr_leave_applications_start_date'), table_name='dsr_leave_applications')
    op.drop_index(op.f('ix_dsr_leave_applications_public_id'), table_name='dsr_leave_applications')
    op.drop_index(op.f('ix_dsr_leave_applications_leave_type'), table_name='dsr_leave_applications')
    op.drop_index(op.f('ix_dsr_leave_applications_is_deleted'), table_name='dsr_leave_applications')
    op.drop_index(op.f('ix_dsr_leave_applications_id'), table_name='dsr_leave_applications')
    op.drop_index(op.f('ix_dsr_leave_applications_end_date'), table_name='dsr_leave_applications')
    op.drop_table('dsr_leave_applications')
    # ### end Alembic commands ###
