"""add_category_to_dsr_activity_types

Revision ID: 4b51035e224f
Revises: efe3746623c0
Create Date: 2026-03-25 08:28:41.353525

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b51035e224f'
down_revision: Union[str, None] = 'efe3746623c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsr_activity_types', sa.Column('category', sa.String(length=50), nullable=True, comment="Grouping category e.g. 'Sourcing', 'Training'"))
    op.create_index(op.f('ix_dsr_activity_types_category'), 'dsr_activity_types', ['category'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_dsr_activity_types_category'), table_name='dsr_activity_types')
    op.drop_column('dsr_activity_types', 'category')
    # ### end Alembic commands ###
