"""add_seb_fields_to_assessment

Revision ID: 59e71c3daafb
Revises: 326ff080830b
Create Date: 2026-02-15 00:24:31.893382

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e71c3daafb'
down_revision: Union[str, None] = '326ff080830b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('include_seb', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('assessments', sa.Column('seb_config_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'seb_config_key')
    op.drop_column('assessments', 'include_seb')
    # ### end Alembic commands ###
