"""drop assessment tables

Revision ID: 3c93c33a03ca
Revises: 456b15c9fe7d
Create Date: 2026-03-28 08:37:46.956229

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c93c33a03ca'
down_revision: Union[str, None] = '456b15c9fe7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop assessment_responses first (no dependents)
    op.drop_index('ix_assessment_responses_id', table_name='assessment_responses')
    op.drop_index('ix_assessment_responses_is_deleted', table_name='assessment_responses')
    op.drop_index('ix_assessment_responses_question_id', table_name='assessment_responses')
    op.drop_index('ix_assessment_responses_result_id', table_name='assessment_responses')
    op.drop_table('assessment_responses')

    # Drop assessment_questions and assessment_results
    op.drop_index('ix_assessment_questions_assessment_id', table_name='assessment_questions')
    op.drop_index('ix_assessment_questions_id', table_name='assessment_questions')
    op.drop_index('ix_assessment_questions_is_deleted', table_name='assessment_questions')
    op.drop_table('assessment_questions')

    op.drop_index('ix_assessment_results_assessment_id', table_name='assessment_results')
    op.drop_index('ix_assessment_results_candidate_id', table_name='assessment_results')
    op.drop_index('ix_assessment_results_id', table_name='assessment_results')
    op.drop_index('ix_assessment_results_is_deleted', table_name='assessment_results')
    op.drop_table('assessment_results')

    # Finally drop assessments
    op.drop_index('ix_assessments_batch_id', table_name='assessments')
    op.drop_index('ix_assessments_id', table_name='assessments')
    op.drop_index('ix_assessments_is_deleted', table_name='assessments')
    op.drop_index('ix_assessments_public_id', table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_results',
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('others', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('assessment_results_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_results_assessment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='assessment_results_candidate_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_results_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_assessment_results_is_deleted', 'assessment_results', ['is_deleted'], unique=False)
    op.create_index('ix_assessment_results_id', 'assessment_results', ['id'], unique=False)
    op.create_index('ix_assessment_results_candidate_id', 'assessment_results', ['candidate_id'], unique=False)
    op.create_index('ix_assessment_results_assessment_id', 'assessment_results', ['assessment_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('others', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], name='assessment_responses_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['assessment_results.id'], name='assessment_responses_result_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_responses_pkey')
    )
    op.create_index('ix_assessment_responses_result_id', 'assessment_responses', ['result_id'], unique=False)
    op.create_index('ix_assessment_responses_question_id', 'assessment_responses', ['question_id'], unique=False)
    op.create_index('ix_assessment_responses_is_deleted', 'assessment_responses', ['is_deleted'], unique=False)
    op.create_index('ix_assessment_responses_id', 'assessment_responses', ['id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('marks', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('others', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_questions_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_questions_pkey')
    )
    op.create_index('ix_assessment_questions_is_deleted', 'assessment_questions', ['is_deleted'], unique=False)
    op.create_index('ix_assessment_questions_id', 'assessment_questions', ['id'], unique=False)
    op.create_index('ix_assessment_questions_assessment_id', 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('assessments',
    sa.Column('public_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('security_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pass_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('others', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('include_seb', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('seb_config_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], name='assessments_batch_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessments_pkey')
    )
    op.create_index('ix_assessments_public_id', 'assessments', ['public_id'], unique=True)
    op.create_index('ix_assessments_is_deleted', 'assessments', ['is_deleted'], unique=False)
    op.create_index('ix_assessments_id', 'assessments', ['id'], unique=False)
    op.create_index('ix_assessments_batch_id', 'assessments', ['batch_id'], unique=False)
    # ### end Alembic commands ###
