"""Add training candidate analysis

Revision ID: d696de986660
Revises: add_created_by_to_skills
Create Date: 2026-05-29 09:43:06.941577

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd696de986660'
down_revision: Union[str, None] = 'add_created_by_to_skills'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_candidate_analysis',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('technical_rating', sa.Float(), nullable=False),
    sa.Column('communication_rating', sa.Float(), nullable=False),
    sa.Column('attitude_rating', sa.Float(), nullable=False),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_candidate_analysis_batch_id'), 'training_candidate_analysis', ['batch_id'], unique=False)
    op.create_index(op.f('ix_training_candidate_analysis_candidate_id'), 'training_candidate_analysis', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_training_candidate_analysis_id'), 'training_candidate_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_training_candidate_analysis_is_deleted'), 'training_candidate_analysis', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_training_candidate_analysis_recommendation'), 'training_candidate_analysis', ['recommendation'], unique=False)
    op.create_index(op.f('ix_training_candidate_analysis_status'), 'training_candidate_analysis', ['status'], unique=False)
    op.alter_column('placement_mappings', 'score_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='ai | rule_based',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('placement_mappings', 'score_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'rule_based'::character varying"),
               existing_comment='ai | rule_based',
               existing_nullable=True)
    op.drop_index(op.f('ix_training_candidate_analysis_status'), table_name='training_candidate_analysis')
    op.drop_index(op.f('ix_training_candidate_analysis_recommendation'), table_name='training_candidate_analysis')
    op.drop_index(op.f('ix_training_candidate_analysis_is_deleted'), table_name='training_candidate_analysis')
    op.drop_index(op.f('ix_training_candidate_analysis_id'), table_name='training_candidate_analysis')
    op.drop_index(op.f('ix_training_candidate_analysis_candidate_id'), table_name='training_candidate_analysis')
    op.drop_index(op.f('ix_training_candidate_analysis_batch_id'), table_name='training_candidate_analysis')
    op.drop_table('training_candidate_analysis')
    # ### end Alembic commands ###
