"""add_consent_fields_to_screening

Revision ID: da77abe5ebc5
Revises: 7c80119ce570
Create Date: 2026-04-25 22:46:26.892412

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da77abe5ebc5'
down_revision: Union[str, None] = '7c80119ce570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_screenings', sa.Column('consent_status', sa.String(length=50), nullable=True))
    op.add_column('candidate_screenings', sa.Column('consent_at', sa.DateTime(), nullable=True))
    op.add_column('candidate_screenings', sa.Column('consent_ip', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_screenings', 'consent_ip')
    op.drop_column('candidate_screenings', 'consent_at')
    op.drop_column('candidate_screenings', 'consent_status')
    # ### end Alembic commands ###
