"""add_crm_tables_company_contact_lead_deal_task

Revision ID: 95b55917a28a
Revises: 5bfd992e03c4
Create Date: 2026-01-15 18:32:31.265801

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b55917a28a'
down_revision: Union[str, None] = '5bfd992e03c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Companies (No dependencies)
    op.create_table('companies',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.Enum('micro', 'small', 'medium', 'large', 'enterprise', name='companysize'), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'prospect', 'customer', name='companystatus'), nullable=False),
    sa.Column('address', sa.JSON(), nullable=True, comment='Company address details: street, city, state, country, pincode'),
    sa.Column('social_media', sa.JSON(), nullable=True, comment='Social media profiles: linkedin, twitter, facebook'),
    sa.Column('custom_fields', sa.JSON(), nullable=True, comment='Extensible custom data for company'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_public_id'), 'companies', ['public_id'], unique=True)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)

    # 2. Contacts (Depends on companies)
    op.create_table('contacts',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Primary contact for the company'),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('contact_source', sa.Enum('website', 'referral', 'event', 'cold_call', 'linkedin', 'other', name='contactsource'), nullable=True),
    sa.Column('contact_preferences', sa.JSON(), nullable=True, comment='Communication preferences: preferred_method, best_time_to_call, timezone, language'),
    sa.Column('address', sa.JSON(), nullable=True, comment='Contact address if different from company'),
    sa.Column('custom_fields', sa.JSON(), nullable=True, comment='Extensible custom data for contact'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_contact_source'), 'contacts', ['contact_source'], unique=False)
    op.create_index(op.f('ix_contacts_designation'), 'contacts', ['designation'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_is_deleted'), 'contacts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    op.create_index(op.f('ix_contacts_public_id'), 'contacts', ['public_id'], unique=True)

    # 3. Leads (Depends on companies, contacts. Skip deals FK for now)
    op.create_table('leads',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=False, comment='Sales rep responsible for this lead'),
    sa.Column('converted_to_deal_id', sa.Integer(), nullable=True, comment='Deal ID if this lead was converted'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_source', sa.Enum('website', 'referral', 'campaign', 'event', 'cold_call', 'social_media', 'partner', name='leadsource'), nullable=False),
    sa.Column('lead_status', sa.Enum('new', 'contacted', 'qualified', 'unqualified', 'lost', name='leadstatus'), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False, comment='Lead scoring 0-100'),
    sa.Column('estimated_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('conversion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Array of tags for categorization'),
    sa.Column('qualification_notes', sa.JSON(), nullable=True, comment='BANT/CHAMP qualification: budget, authority, need, timeline, pain_points'),
    sa.Column('utm_data', sa.JSON(), nullable=True, comment='Marketing attribution: utm_source, utm_medium, utm_campaign, landing_page'),
    sa.Column('custom_fields', sa.JSON(), nullable=True, comment='Extensible custom data for lead'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_expected_close_date'), 'leads', ['expected_close_date'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_is_deleted'), 'leads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_lead_source'), 'leads', ['lead_source'], unique=False)
    op.create_index(op.f('ix_leads_lead_status'), 'leads', ['lead_status'], unique=False)
    op.create_index(op.f('ix_leads_public_id'), 'leads', ['public_id'], unique=True)
    op.create_index(op.f('ix_leads_title'), 'leads', ['title'], unique=False)

    # 4. Deals (Depends on companies, contacts, leads)
    op.create_table('deals',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True, comment='Original lead if converted from lead'),
    sa.Column('assigned_to', sa.Integer(), nullable=False, comment='Account owner responsible for this deal'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deal_stage', sa.Enum('discovery', 'qualification', 'proposal', 'negotiation', 'closed_won', 'closed_lost', name='dealstage'), nullable=False),
    sa.Column('deal_type', sa.Enum('new_business', 'upsell', 'renewal', 'cross_sell', name='dealtype'), nullable=False),
    sa.Column('win_probability', sa.Integer(), nullable=False, comment='Win probability percentage 0-100'),
    sa.Column('deal_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('contract_duration_months', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=False),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('lost_reason', sa.String(length=255), nullable=True),
    sa.Column('lost_to_competitor', sa.String(length=255), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True, comment='Array of competitor information'),
    sa.Column('products_services', sa.JSON(), nullable=True, comment='Items in the deal: product_id, name, quantity, unit_price, discount, total'),
    sa.Column('next_action', sa.JSON(), nullable=True, comment='Next action details: action, due_date, assigned_to'),
    sa.Column('custom_fields', sa.JSON(), nullable=True, comment='Extensible custom data for deal'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_assigned_to'), 'deals', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_contact_id'), 'deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_deals_deal_stage'), 'deals', ['deal_stage'], unique=False)
    op.create_index(op.f('ix_deals_deal_type'), 'deals', ['deal_type'], unique=False)
    op.create_index(op.f('ix_deals_deal_value'), 'deals', ['deal_value'], unique=False)
    op.create_index(op.f('ix_deals_expected_close_date'), 'deals', ['expected_close_date'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_is_deleted'), 'deals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_deals_public_id'), 'deals', ['public_id'], unique=True)
    op.create_index(op.f('ix_deals_title'), 'deals', ['title'], unique=False)

    # 5. Leads Post-processing (Add the circular FK to deals)
    op.create_foreign_key('fk_leads_converted_to_deal_id_deals', 'leads', 'deals', ['converted_to_deal_id'], ['id'], ondelete='SET NULL')

    # 6. Activity Logs
    op.create_table('crm_activity_logs',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('company', 'contact', 'lead', 'deal', 'task', name='crmentitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('created', 'updated', 'deleted', 'status_changed', 'email_sent', 'call_made', 'meeting_held', 'note_added', 'stage_changed', 'converted', name='crmactivitytype'), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True, comment='Detailed activity data: old_value, new_value, field_changed, ip_address, user_agent'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='Additional context for the activity'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_activity_logs_activity_type'), 'crm_activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_crm_activity_logs_entity_id'), 'crm_activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_activity_logs_entity_type'), 'crm_activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_crm_activity_logs_id'), 'crm_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_crm_activity_logs_is_deleted'), 'crm_activity_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_activity_logs_performed_by'), 'crm_activity_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_crm_activity_logs_public_id'), 'crm_activity_logs', ['public_id'], unique=True)

    # 7. CRM Tasks
    op.create_table('crm_tasks',
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('call', 'email', 'meeting', 'follow_up', 'demo', 'proposal', 'other', name='crmtasktype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='crmtaskpriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='crmtaskstatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('related_to_type', sa.Enum('lead', 'deal', 'company', 'contact', name='crmrelatedtotype'), nullable=True),
    sa.Column('related_to_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_before_minutes', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=True, comment='Result of task: status, notes, next_steps, time_spent_minutes'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='File references: file_name, file_url, uploaded_at'),
    sa.Column('custom_fields', sa.JSON(), nullable=True, comment='Extensible custom data for task'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tasks_assigned_to'), 'crm_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_crm_tasks_due_date'), 'crm_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_crm_tasks_id'), 'crm_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_is_deleted'), 'crm_tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_tasks_priority'), 'crm_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_crm_tasks_public_id'), 'crm_tasks', ['public_id'], unique=True)
    op.create_index(op.f('ix_crm_tasks_related_to_id'), 'crm_tasks', ['related_to_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_related_to_type'), 'crm_tasks', ['related_to_type'], unique=False)
    op.create_index(op.f('ix_crm_tasks_status'), 'crm_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_crm_tasks_task_type'), 'crm_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_crm_tasks_title'), 'crm_tasks', ['title'], unique=False)

    # 8. Users Table Updates
    op.add_column('users', sa.Column('team', sa.String(length=100), nullable=True, comment='Sales team assignment'))
    op.add_column('users', sa.Column('sales_quota_monthly', sa.Numeric(precision=15, scale=2), nullable=True, comment='Monthly sales target'))
    op.add_column('users', sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Commission rate'))
    op.create_index(op.f('ix_users_team'), 'users', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_team'), table_name='users')
    op.drop_column('users', 'commission_percentage')
    op.drop_column('users', 'sales_quota_monthly')
    op.drop_column('users', 'team')
    op.drop_index(op.f('ix_crm_tasks_title'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_task_type'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_status'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_related_to_type'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_related_to_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_public_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_priority'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_is_deleted'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_due_date'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_assigned_to'), table_name='crm_tasks')
    op.drop_table('crm_tasks')
    op.drop_index(op.f('ix_crm_activity_logs_public_id'), table_name='crm_activity_logs')
    op.drop_index(op.f('ix_crm_activity_logs_performed_by'), table_name='crm_activity_logs')
    op.drop_index(op.f('ix_crm_activity_logs_is_deleted'), table_name='crm_activity_logs')
    op.drop_index(op.f('ix_crm_activity_logs_id'), table_name='crm_activity_logs')
    op.drop_index(op.f('ix_crm_activity_logs_entity_type'), table_name='crm_activity_logs')
    op.drop_index(op.f('ix_crm_activity_logs_entity_id'), table_name='crm_activity_logs')
    op.drop_index(op.f('ix_crm_activity_logs_activity_type'), table_name='crm_activity_logs')
    op.drop_table('crm_activity_logs')
    
    # Remove the circular FK from leads before dropping deals
    op.drop_constraint('fk_leads_converted_to_deal_id_deals', 'leads', type_='foreignkey')
    
    op.drop_index(op.f('ix_deals_title'), table_name='deals')
    op.drop_index(op.f('ix_deals_public_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_is_deleted'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_expected_close_date'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_value'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_type'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_contact_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_assigned_to'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_leads_title'), table_name='leads')
    op.drop_index(op.f('ix_leads_public_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_deleted'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_expected_close_date'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_contacts_public_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_deleted'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_designation'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_source'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_public_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
