"""Add Mock Interview tables

Revision ID: c56fe0031c0e
Revises: 44e461eebbb1
Create Date: 2026-01-11 14:51:18.395817

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56fe0031c0e'
down_revision: Union[str, None] = '44e461eebbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_mock_interviews', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('training_mock_interviews', sa.Column('others', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_mock_interviews', 'others')
    op.drop_column('training_mock_interviews', 'skills')
    # ### end Alembic commands ###
