"""Add other JSON column to candidate analysis

Revision ID: e696de986662
Revises: e696de986661
Create Date: 2026-06-01 11:45:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e696de986662'
down_revision: Union[str, None] = 'e696de986661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_candidate_analysis', sa.Column('other', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_candidate_analysis', 'other')
    # ### end Alembic commands ###
