"""add_offer_letter_id_to_placement_offers

Revision ID: b0d5f17bf7f1
Revises: 779a3a0ef8a1
Create Date: 2026-04-24 15:30:26.024679

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d5f17bf7f1'
down_revision: Union[str, None] = '779a3a0ef8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placement_offers', sa.Column('offer_letter_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_placement_offers_offer_letter_id', 'placement_offers', 'candidate_documents', ['offer_letter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_placement_offers_offer_letter_id', 'placement_offers', type_='foreignkey')
    op.drop_column('placement_offers', 'offer_letter_id')
    # ### end Alembic commands ###
