"""add_disability_preferred_to_job_role_metadata

Revision ID: 9b1e6a0b774f
Revises: 3af887c65ae3
Create Date: 2026-03-28 12:03:31.649445

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b1e6a0b774f'
down_revision: Union[str, None] = '3af887c65ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_roles', 'requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='{"skills": [], "qualifications": [], "disability_preferred": []}',
               existing_comment='{"skills": [], "qualifications": []}',
               existing_nullable=True)
    
    # Data migration: Initialize disability_preferred for existing job roles
    # We use a raw SQL execution to handle JSON manipulation in PostgreSQL
    op.execute(
        """
        UPDATE job_roles 
        SET requirements = (requirements::jsonb || '{"disability_preferred": []}'::jsonb)::json 
        WHERE requirements IS NOT NULL 
        AND NOT (requirements::jsonb ? 'disability_preferred');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Data migration: Remove disability_preferred from requirements for downgrade
    op.execute(
        """
        UPDATE job_roles 
        SET requirements = (requirements::jsonb - 'disability_preferred')::json 
        WHERE requirements IS NOT NULL;
        """
    )

    op.alter_column('job_roles', 'requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='{"skills": [], "qualifications": []}',
               existing_comment='{"skills": [], "qualifications": [], "disability_preferred": []}',
               existing_nullable=True)
    # ### end Alembic commands ###
