"""Add screened_by_id to candidate_screening

Revision ID: 6162ecedebcb
Revises: c44149706de5
Create Date: 2026-01-19 22:40:30.111374

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6162ecedebcb'
down_revision: Union[str, None] = 'c44149706de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_screenings', sa.Column('screened_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate_screenings', 'users', ['screened_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_screenings', type_='foreignkey')
    op.drop_column('candidate_screenings', 'screened_by_id')
    # ### end Alembic commands ###
