"""drop rating columns from candidate analysis

Revision ID: 85d7b45969f0
Revises: e696de986662
Create Date: 2026-06-01 12:19:12.719121

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d7b45969f0'
down_revision: Union[str, None] = 'e696de986662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_candidate_analysis', 'attitude_rating')
    op.drop_column('training_candidate_analysis', 'overall_rating')
    op.drop_column('training_candidate_analysis', 'technical_rating')
    op.drop_column('training_candidate_analysis', 'communication_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_candidate_analysis', sa.Column('communication_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('training_candidate_analysis', sa.Column('technical_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('training_candidate_analysis', sa.Column('overall_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('training_candidate_analysis', sa.Column('attitude_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
