"""Add candidate_screening_assignments table

Revision ID: 6c0a00577ecc
Revises: 59e71c3daafb
Create Date: 2026-02-20 18:34:16.287196

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0a00577ecc'
down_revision: Union[str, None] = '59e71c3daafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_screening_assignments',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_screening_assignments_assigned_to_id'), 'candidate_screening_assignments', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_candidate_screening_assignments_candidate_id'), 'candidate_screening_assignments', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_screening_assignments_id'), 'candidate_screening_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_screening_assignments_is_deleted'), 'candidate_screening_assignments', ['is_deleted'], unique=False)
    op.alter_column('assessments', 'include_seb',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'include_seb',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_candidate_screening_assignments_is_deleted'), table_name='candidate_screening_assignments')
    op.drop_index(op.f('ix_candidate_screening_assignments_id'), table_name='candidate_screening_assignments')
    op.drop_index(op.f('ix_candidate_screening_assignments_candidate_id'), table_name='candidate_screening_assignments')
    op.drop_index(op.f('ix_candidate_screening_assignments_assigned_to_id'), table_name='candidate_screening_assignments')
    op.drop_table('candidate_screening_assignments')
    # ### end Alembic commands ###
