"""add dsr_permission_requests table

Revision ID: 7063d510cef2
Revises: 6d14b47db469
Create Date: 2026-03-07 22:09:43.434872

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7063d510cef2'
down_revision: Union[str, None] = '6d14b47db469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsr_permission_requests',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'granted', 'rejected', name='dsrpermissionstatus'), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_permission_requests_id'), 'dsr_permission_requests', ['id'], unique=False)
    op.create_index(op.f('ix_dsr_permission_requests_is_deleted'), 'dsr_permission_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dsr_permission_requests_public_id'), 'dsr_permission_requests', ['public_id'], unique=True)
    op.create_index(op.f('ix_dsr_permission_requests_report_date'), 'dsr_permission_requests', ['report_date'], unique=False)
    op.create_index(op.f('ix_dsr_permission_requests_status'), 'dsr_permission_requests', ['status'], unique=False)
    op.create_index(op.f('ix_dsr_permission_requests_user_id'), 'dsr_permission_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsr_permission_requests_user_id'), table_name='dsr_permission_requests')
    op.drop_index(op.f('ix_dsr_permission_requests_status'), table_name='dsr_permission_requests')
    op.drop_index(op.f('ix_dsr_permission_requests_report_date'), table_name='dsr_permission_requests')
    op.drop_index(op.f('ix_dsr_permission_requests_public_id'), table_name='dsr_permission_requests')
    op.drop_index(op.f('ix_dsr_permission_requests_is_deleted'), table_name='dsr_permission_requests')
    op.drop_index(op.f('ix_dsr_permission_requests_id'), table_name='dsr_permission_requests')
    op.drop_table('dsr_permission_requests')
    # ### end Alembic commands ###
