"""Add training batch fields

Revision ID: f580dca92b5d
Revises: d4617ead414c
Create Date: 2026-01-08 20:56:56.783996

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f580dca92b5d'
down_revision: Union[str, None] = 'd4617ead414c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_batches', sa.Column('disability_type', sa.String(length=255), nullable=True))
    op.add_column('training_batches', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('training_batches', sa.Column('approx_close_date', sa.Date(), nullable=True))
    op.add_column('training_batches', sa.Column('total_extension_days', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_batches', 'total_extension_days')
    op.drop_column('training_batches', 'approx_close_date')
    op.drop_column('training_batches', 'start_date')
    op.drop_column('training_batches', 'disability_type')
    # ### end Alembic commands ###
