"""Add period_id and trainer_notes

Revision ID: 20cdfca4b79b
Revises: e1a06a40bdd2
Create Date: 2026-02-14 22:38:02.140918

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cdfca4b79b'
down_revision: Union[str, None] = 'e1a06a40bdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_attendance', sa.Column('period_id', sa.Integer(), nullable=True))
    op.add_column('training_attendance', sa.Column('trainer_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_training_attendance_period_id'), 'training_attendance', ['period_id'], unique=False)
    op.create_foreign_key(None, 'training_attendance', 'training_batch_plans', ['period_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_attendance', type_='foreignkey')
    op.drop_index(op.f('ix_training_attendance_period_id'), table_name='training_attendance')
    op.drop_column('training_attendance', 'trainer_notes')
    op.drop_column('training_attendance', 'period_id')
    # ### end Alembic commands ###
