"""Add training_batch_plans table

Revision ID: cf5d8bd2e696
Revises: 1f9a0629b648
Create Date: 2026-02-14 09:44:00.111228

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5d8bd2e696'
down_revision: Union[str, None] = '1f9a0629b648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_batch_plans',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('trainer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_batch_plans_batch_id'), 'training_batch_plans', ['batch_id'], unique=False)
    op.create_index(op.f('ix_training_batch_plans_date'), 'training_batch_plans', ['date'], unique=False)
    op.create_index(op.f('ix_training_batch_plans_id'), 'training_batch_plans', ['id'], unique=False)
    op.create_index(op.f('ix_training_batch_plans_is_deleted'), 'training_batch_plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_training_batch_plans_public_id'), 'training_batch_plans', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_batch_plans_public_id'), table_name='training_batch_plans')
    op.drop_index(op.f('ix_training_batch_plans_is_deleted'), table_name='training_batch_plans')
    op.drop_index(op.f('ix_training_batch_plans_id'), table_name='training_batch_plans')
    op.drop_index(op.f('ix_training_batch_plans_date'), table_name='training_batch_plans')
    op.drop_index(op.f('ix_training_batch_plans_batch_id'), table_name='training_batch_plans')
    op.drop_table('training_batch_plans')
    # ### end Alembic commands ###
