"""Add DSR project batch association table

Revision ID: 7e9a1b2c3d4f
Revises: 55b02f01eb45
Create Date: 2026-04-04 17:10:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9a1b2c3d4f'
down_revision: Union[str, None] = '55b02f01eb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsr_project_batch_association',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['batch_id'], ['training_batches.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['dsr_projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('project_id', 'batch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dsr_project_batch_association')
    # ### end Alembic commands ###
