"""add_document_source_to_candidate_documents

Revision ID: 779a3a0ef8a1
Revises: 50660258cbb0
Create Date: 2026-04-21 21:44:21.330614

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '779a3a0ef8a1'
down_revision: Union[str, None] = '50660258cbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable
    op.add_column('candidate_documents', sa.Column('document_source', sa.String(length=50), nullable=True))
    op.add_column('candidate_documents', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('candidate_documents', sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
    
    # Step 2: Update existing rows with defaults
    op.execute("UPDATE candidate_documents SET document_source = 'candidate' WHERE document_source IS NULL")
    op.execute("UPDATE candidate_documents SET is_active = true WHERE is_active IS NULL")
    
    # Step 3: Set columns to NOT NULL
    op.alter_column('candidate_documents', 'document_source', nullable=False)
    op.alter_column('candidate_documents', 'is_active', nullable=False)

    op.create_index(op.f('ix_candidate_documents_document_source'), 'candidate_documents', ['document_source'], unique=False)
    op.create_index(op.f('ix_candidate_documents_is_active'), 'candidate_documents', ['is_active'], unique=False)
    op.create_foreign_key(None, 'candidate_documents', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    
    # Updated job roles stages comment
    op.alter_column('job_roles', 'pipeline_stages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='[{"id": "string", "label": "string", "category": "lead|shortlisted|interview|offer|hired|rejected|not_joined"}]',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_roles', 'pipeline_stages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='[{"id": "string", "label": "string", "category": "lead|shortlisted|interview|offer|hired|rejected|not_joined"}]',
               existing_nullable=True)
    op.drop_constraint(None, 'candidate_documents', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_documents_is_active'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_document_source'), table_name='candidate_documents')
    op.drop_column('candidate_documents', 'uploaded_by_id')
    op.drop_column('candidate_documents', 'is_active')
    op.drop_column('candidate_documents', 'document_source')
    # ### end Alembic commands ###
