"""Add candidate token and interviewer id to mock interviews

Revision ID: 18d26048c49f
Revises: 220f22fca038
Create Date: 2026-05-12 11:43:33.649788

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d26048c49f'
down_revision: Union[str, None] = '220f22fca038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_mock_interviews', sa.Column('interviewer_id', sa.Integer(), nullable=True))
    op.add_column('training_mock_interviews', sa.Column('candidate_token', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_training_mock_interviews_candidate_token'), 'training_mock_interviews', ['candidate_token'], unique=False)
    op.create_foreign_key(None, 'training_mock_interviews', 'users', ['interviewer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_mock_interviews', type_='foreignkey')
    op.drop_index(op.f('ix_training_mock_interviews_candidate_token'), table_name='training_mock_interviews')
    op.drop_column('training_mock_interviews', 'candidate_token')
    op.drop_column('training_mock_interviews', 'interviewer_id')
    # ### end Alembic commands ###
