"""add_user_mobile_column

Revision ID: 0d0cc7756b48
Revises: a9f3b2e1d4c7
Create Date: 2026-03-15 12:26:32.001116

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d0cc7756b48'
down_revision: Union[str, None] = 'a9f3b2e1d4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=True, comment='Professional/Personal mobile number for WhatsApp link'))
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=False)
    op.alter_column('whatsapp_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_comment='Meta message type: text | image | document | audio | video | sticker | location',
               existing_nullable=False)
    op.alter_column('whatsapp_messages', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Timestamp from Meta's webhook payload",
               existing_comment='Timestamp from Meta webhook payload',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('whatsapp_messages', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='Current processing state of this message',
               existing_comment='Current processing state: pending | processed | failed | ignored',
               existing_nullable=False)
    op.alter_column('whatsapp_messages', 'crm_action_taken',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Summary of CRM records created/updated: {lead_id, contact_id, company_id, task_id, activity_id}',
               existing_comment='Summary of CRM records created/updated: {lead_id, contact_id, company_id, task_id}',
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('whatsapp_messages', 'crm_action_taken',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Summary of CRM records created/updated: {lead_id, contact_id, company_id, task_id}',
               existing_comment='Summary of CRM records created/updated: {lead_id, contact_id, company_id, task_id, activity_id}',
               existing_nullable=True)
    op.alter_column('whatsapp_messages', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               comment='Current processing state: pending | processed | failed | ignored',
               existing_comment='Current processing state of this message',
               existing_nullable=False)
    op.alter_column('whatsapp_messages', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp from Meta webhook payload',
               existing_comment="Timestamp from Meta's webhook payload",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('whatsapp_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'text'::character varying"),
               existing_comment='Meta message type: text | image | document | audio | video | sticker | location',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###
