"""expand_activity_type_code_length

Revision ID: cb7f63e0e1b8
Revises: 4b51035e224f
Create Date: 2026-03-25 09:05:21.741965

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7f63e0e1b8'
down_revision: Union[str, None] = '4b51035e224f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsr_activity_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_comment="Short uppercase code e.g. 'DEV' — used in analytics grouping",
               existing_nullable=False)
    op.alter_column('dsr_activity_types', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_comment="Grouping category e.g. 'Sourcing', 'Training'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsr_activity_types', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_comment="Grouping category e.g. 'Sourcing', 'Training'",
               existing_nullable=True)
    op.alter_column('dsr_activity_types', 'code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_comment="Short uppercase code e.g. 'DEV' — used in analytics grouping",
               existing_nullable=False)
    # ### end Alembic commands ###
