"""Add training-aware project intelligence fields

Revision ID: 55b02f01eb45
Revises: 5aa14ff6f88d
Create Date: 2026-04-04 16:39:42.490166

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add training-aware project intelligence fields

Revision ID: 55b02f01eb45
Revises: 5aa14ff6f88d
Create Date: 2026-04-04 16:39:42.490166

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b02f01eb45'
down_revision: Union[str, None] = '5aa14ff6f88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type first
    dsrprojecttype = sa.Enum('standard', 'training', name='dsrprojecttype')
    dsrprojecttype.create(op.get_bind())

    op.add_column('dsr_projects', sa.Column('project_type', sa.Enum('standard', 'training', name='dsrprojecttype'), nullable=False))
    op.add_column('dsr_projects', sa.Column('linked_batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dsr_projects_linked_batch_id'), 'dsr_projects', ['linked_batch_id'], unique=False)
    op.create_index(op.f('ix_dsr_projects_project_type'), 'dsr_projects', ['project_type'], unique=False)
    op.create_foreign_key(None, 'dsr_projects', 'training_batches', ['linked_batch_id'], ['id'], ondelete='SET NULL')
    
    # These seem to be incidental autogenerated changes, keeping them
    op.alter_column('placement_mappings', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('placement_mappings', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    
    op.add_column('training_batch_plans', sa.Column('trainer_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_training_batch_plans_trainer_user_id'), 'training_batch_plans', ['trainer_user_id'], unique=False)
    op.create_foreign_key(None, 'training_batch_plans', 'users', ['trainer_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_batch_plans', type_='foreignkey')
    op.drop_index(op.f('ix_training_batch_plans_trainer_user_id'), table_name='training_batch_plans')
    op.drop_column('training_batch_plans', 'trainer_user_id')
    op.alter_column('placement_mappings', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('placement_mappings', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'applied'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'dsr_projects', type_='foreignkey')
    op.drop_index(op.f('ix_dsr_projects_project_type'), table_name='dsr_projects')
    op.drop_index(op.f('ix_dsr_projects_linked_batch_id'), table_name='dsr_projects')
    op.drop_column('dsr_projects', 'linked_batch_id')
    op.drop_column('dsr_projects', 'project_type')

    # Drop the Enum type
    sa.Enum(name='dsrprojecttype').drop(op.get_bind())
    # ### end Alembic commands ###
