"""Add family_details to candidate_screening

Revision ID: c44149706de5
Revises: 95b55917a28a
Create Date: 2026-01-19 22:02:00.985774

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44149706de5'
down_revision: Union[str, None] = '95b55917a28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_screenings', sa.Column('family_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_screenings', 'family_details')
    # ### end Alembic commands ###
