"""add_placement_tracking_modules

Revision ID: 70aaf3e98b31
Revises: 42bd88790f09
Create Date: 2026-03-29 20:03:01.329713

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aaf3e98b31'
down_revision: Union[str, None] = '42bd88790f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # We use String(50) instead of Enum to avoid Postgres migration headaches
    # Validation is handled at the model and API levels
    op.create_table('placement_interviews',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('conducted_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('interviewer_name', sa.String(length=255), nullable=True),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.Column('interview_link', sa.String(length=500), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('feedback_json', sa.JSON(), nullable=True, comment='{"communication": float, "tech": float, "culture": float, "comments": ""}'),
    sa.Column('scheduled_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapping_id'], ['placement_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_interviews_candidate_id'), 'placement_interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_placement_interviews_id'), 'placement_interviews', ['id'], unique=False)
    op.create_index(op.f('ix_placement_interviews_is_deleted'), 'placement_interviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_interviews_job_role_id'), 'placement_interviews', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_placement_interviews_mapping_id'), 'placement_interviews', ['mapping_id'], unique=False)
    op.create_table('placement_notes',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapping_id'], ['placement_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_notes_candidate_id'), 'placement_notes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_placement_notes_id'), 'placement_notes', ['id'], unique=False)
    op.create_index(op.f('ix_placement_notes_is_deleted'), 'placement_notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_notes_job_role_id'), 'placement_notes', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_placement_notes_mapping_id'), 'placement_notes', ['mapping_id'], unique=False)
    op.create_table('placement_offers',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=False),
    sa.Column('offered_ctc', sa.Float(), nullable=True),
    sa.Column('offered_designation', sa.String(length=255), nullable=True),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('offer_letter_url', sa.String(length=500), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('response_deadline', sa.Date(), nullable=True),
    sa.Column('candidate_response', sa.String(length=50), nullable=False),
    sa.Column('response_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('actual_joining_date', sa.Date(), nullable=True),
    sa.Column('joining_status', sa.String(length=50), nullable=True),
    sa.Column('offered_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapping_id'], ['placement_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_offers_candidate_id'), 'placement_offers', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_placement_offers_id'), 'placement_offers', ['id'], unique=False)
    op.create_index(op.f('ix_placement_offers_is_deleted'), 'placement_offers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_offers_job_role_id'), 'placement_offers', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_placement_offers_mapping_id'), 'placement_offers', ['mapping_id'], unique=True)
    op.create_table('placement_pipeline_history',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapping_id'], ['placement_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_pipeline_history_candidate_id'), 'placement_pipeline_history', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_placement_pipeline_history_id'), 'placement_pipeline_history', ['id'], unique=False)
    op.create_index(op.f('ix_placement_pipeline_history_is_deleted'), 'placement_pipeline_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_pipeline_history_job_role_id'), 'placement_pipeline_history', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_placement_pipeline_history_mapping_id'), 'placement_pipeline_history', ['mapping_id'], unique=False)
    op.add_column('placement_mappings', sa.Column('status', sa.String(length=50), nullable=False, server_default='applied'))
    op.add_column('placement_mappings', sa.Column('priority', sa.String(length=20), nullable=True, comment='high, medium, low'))
    op.add_column('placement_mappings', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('placement_mappings', sa.Column('unmapped_by_id', sa.Integer(), nullable=True))
    op.add_column('placement_mappings', sa.Column('unmapped_at', sa.DateTime(), nullable=True))
    op.add_column('placement_mappings', sa.Column('unmapped_reason', sa.Text(), nullable=True))
    op.add_column('placement_mappings', sa.Column('source', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_placement_mappings_status'), 'placement_mappings', ['status'], unique=False)
    op.create_foreign_key(None, 'placement_mappings', 'users', ['unmapped_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'placement_mappings', type_='foreignkey')
    op.drop_index(op.f('ix_placement_mappings_status'), table_name='placement_mappings')
    op.drop_column('placement_mappings', 'source')
    op.drop_column('placement_mappings', 'unmapped_reason')
    op.drop_column('placement_mappings', 'unmapped_at')
    op.drop_column('placement_mappings', 'unmapped_by_id')
    op.drop_column('placement_mappings', 'is_active')
    op.drop_column('placement_mappings', 'priority')
    op.drop_column('placement_mappings', 'status')
    op.drop_index(op.f('ix_placement_pipeline_history_mapping_id'), table_name='placement_pipeline_history')
    op.drop_index(op.f('ix_placement_pipeline_history_job_role_id'), table_name='placement_pipeline_history')
    op.drop_index(op.f('ix_placement_pipeline_history_is_deleted'), table_name='placement_pipeline_history')
    op.drop_index(op.f('ix_placement_pipeline_history_id'), table_name='placement_pipeline_history')
    op.drop_index(op.f('ix_placement_pipeline_history_candidate_id'), table_name='placement_pipeline_history')
    op.drop_table('placement_pipeline_history')
    op.drop_index(op.f('ix_placement_offers_mapping_id'), table_name='placement_offers')
    op.drop_index(op.f('ix_placement_offers_job_role_id'), table_name='placement_offers')
    op.drop_index(op.f('ix_placement_offers_is_deleted'), table_name='placement_offers')
    op.drop_index(op.f('ix_placement_offers_id'), table_name='placement_offers')
    op.drop_index(op.f('ix_placement_offers_candidate_id'), table_name='placement_offers')
    op.drop_table('placement_offers')
    op.drop_index(op.f('ix_placement_notes_mapping_id'), table_name='placement_notes')
    op.drop_index(op.f('ix_placement_notes_job_role_id'), table_name='placement_notes')
    op.drop_index(op.f('ix_placement_notes_is_deleted'), table_name='placement_notes')
    op.drop_index(op.f('ix_placement_notes_id'), table_name='placement_notes')
    op.drop_index(op.f('ix_placement_notes_candidate_id'), table_name='placement_notes')
    op.drop_table('placement_notes')
    op.drop_index(op.f('ix_placement_interviews_mapping_id'), table_name='placement_interviews')
    op.drop_index(op.f('ix_placement_interviews_job_role_id'), table_name='placement_interviews')
    op.drop_index(op.f('ix_placement_interviews_is_deleted'), table_name='placement_interviews')
    op.drop_index(op.f('ix_placement_interviews_id'), table_name='placement_interviews')
    op.drop_index(op.f('ix_placement_interviews_candidate_id'), table_name='placement_interviews')
    op.drop_table('placement_interviews')
    # ### end Alembic commands ###
