"""add_reason_fields_to_job_role

Revision ID: 5bf0ac3fdf61
Revises: 4b9435006cfe
Create Date: 2026-05-13 15:42:04.153390

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf0ac3fdf61'
down_revision: Union[str, None] = '4b9435006cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_roles', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('job_roles', sa.Column('deletion_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_roles', 'deletion_reason')
    op.drop_column('job_roles', 'status_reason')
    # ### end Alembic commands ###
