"""Add owner_id to training_batches

Revision ID: 629040c87304
Revises: 85d7b45969f0
Create Date: 2026-06-03 11:15:48.821934

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629040c87304'
down_revision: Union[str, None] = '85d7b45969f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_batches', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_training_batches_owner_id'), 'training_batches', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'training_batches', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_batches', type_='foreignkey')
    op.drop_index(op.f('ix_training_batches_owner_id'), table_name='training_batches')
    op.drop_column('training_batches', 'owner_id')
    # ### end Alembic commands ###
