"""add_temporal_and_type_fields_to_mock_interview

Revision ID: d4dab2ba591d
Revises: da77abe5ebc5
Create Date: 2026-05-06 12:12:58.297820

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4dab2ba591d'
down_revision: Union[str, None] = 'da77abe5ebc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_mock_interviews', sa.Column('interview_type', sa.String(length=20), nullable=True))
    op.add_column('training_mock_interviews', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('training_mock_interviews', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('training_mock_interviews', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_mock_interviews', 'duration_minutes')
    op.drop_column('training_mock_interviews', 'end_time')
    op.drop_column('training_mock_interviews', 'start_time')
    op.drop_column('training_mock_interviews', 'interview_type')
    # ### end Alembic commands ###
