"""Strict candidate allocation status

Revision ID: 1986f22b0e89
Revises: cf5d8bd2e696
Create Date: 2026-02-14 19:09:50.291705

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1986f22b0e89'
down_revision: Union[str, None] = 'cf5d8bd2e696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_candidate_allocations', 'status',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_training_candidate_allocations_status'), 'training_candidate_allocations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_candidate_allocations_status'), table_name='training_candidate_allocations')
    op.alter_column('training_candidate_allocations', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
