"""add_dsr_activity_types

Revision ID: edc35884e24e
Revises: d036b2b280fd
Create Date: 2026-03-12 11:37:39.000181

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc35884e24e'
down_revision: Union[str, None] = 'd036b2b280fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsr_activity_types',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Display name e.g. 'Development'"),
    sa.Column('code', sa.String(length=20), nullable=False, comment="Short uppercase code e.g. 'DEV' — used in analytics grouping"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of this activity type'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Controls display order in dropdowns (ascending)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_activity_types_code'), 'dsr_activity_types', ['code'], unique=True)
    op.create_index(op.f('ix_dsr_activity_types_id'), 'dsr_activity_types', ['id'], unique=False)
    op.create_index(op.f('ix_dsr_activity_types_is_active'), 'dsr_activity_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_dsr_activity_types_is_deleted'), 'dsr_activity_types', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dsr_activity_types_name'), 'dsr_activity_types', ['name'], unique=False)
    op.create_index(op.f('ix_dsr_activity_types_public_id'), 'dsr_activity_types', ['public_id'], unique=True)
    # ### end Alembic commands ###

    # ── Seed default activity types ────────────────────────────────────────
    import uuid as _uuid
    activity_types_table = sa.table(
        'dsr_activity_types',
        sa.column('public_id', sa.Uuid()),
        sa.column('name', sa.String()),
        sa.column('code', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('is_active', sa.Boolean()),
        sa.column('sort_order', sa.Integer()),
        sa.column('is_deleted', sa.Boolean()),
    )
    seed_data = [
        ("Development",          "DEV",     "Writing, reviewing, or debugging code",                       0),
        ("Testing / QA",         "TEST",    "Manual or automated testing, quality assurance activities",   1),
        ("Meetings",             "MEET",    "Internal meetings, stand-ups, client calls",                  2),
        ("Documentation",        "DOC",     "Writing specs, guides, reports, or internal docs",            3),
        ("Training",             "TRAIN",   "Conducting or attending training sessions",                   4),
        ("Code Review",          "REVIEW",  "Reviewing pull requests or work deliverables",                5),
        ("Support / Bug Fixes",  "SUPPORT", "Responding to issues, bug fixes, user support",               6),
        ("Administrative",       "ADMIN",   "Administrative tasks, HR activities, compliance",             7),
        ("Design / UI/UX",       "DESIGN",  "UI design, wireframing, prototyping",                         8),
        ("Deployment / DevOps",  "DEPLOY",  "Deployments, infrastructure, CI/CD pipeline work",            9),
    ]
    op.bulk_insert(
        activity_types_table,
        [
            {
                "public_id": _uuid.uuid4(),
                "name": name,
                "code": code,
                "description": desc,
                "is_active": True,
                "sort_order": order,
                "is_deleted": False,
            }
            for name, code, desc, order in seed_data
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsr_activity_types_public_id'), table_name='dsr_activity_types')
    op.drop_index(op.f('ix_dsr_activity_types_name'), table_name='dsr_activity_types')
    op.drop_index(op.f('ix_dsr_activity_types_is_deleted'), table_name='dsr_activity_types')
    op.drop_index(op.f('ix_dsr_activity_types_is_active'), table_name='dsr_activity_types')
    op.drop_index(op.f('ix_dsr_activity_types_id'), table_name='dsr_activity_types')
    op.drop_index(op.f('ix_dsr_activity_types_code'), table_name='dsr_activity_types')
    op.drop_table('dsr_activity_types')
    # ### end Alembic commands ###
