"""make dsr activity dates optional

Revision ID: 456b15c9fe7d
Revises: cb7f63e0e1b8
Create Date: 2026-03-26 10:09:54.095473

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456b15c9fe7d'
down_revision: Union[str, None] = 'cb7f63e0e1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsr_activities', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('dsr_activities', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsr_activities', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('dsr_activities', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
