"""create candidate pool table

Revision ID: 62518262b7bb
Revises: 5bf0ac3fdf61
Create Date: 2026-05-13 17:41:56.674629

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62518262b7bb'
down_revision: Union[str, None] = '5bf0ac3fdf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_pool',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('disability_category', sa.String(length=255), nullable=True),
    sa.Column('disability_sub_category', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('placement_details', sa.JSON(), nullable=True),
    sa.Column('status_of_beneficiary', sa.String(length=100), nullable=True),
    sa.Column('donor', sa.JSON(), nullable=True),
    sa.Column('batch_year', sa.String(length=50), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_pool_email'), 'candidate_pool', ['email'], unique=False)
    op.create_index(op.f('ix_candidate_pool_id'), 'candidate_pool', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_pool_is_deleted'), 'candidate_pool', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_pool_name'), 'candidate_pool', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_pool_name'), table_name='candidate_pool')
    op.drop_index(op.f('ix_candidate_pool_is_deleted'), table_name='candidate_pool')
    op.drop_index(op.f('ix_candidate_pool_id'), table_name='candidate_pool')
    op.drop_index(op.f('ix_candidate_pool_email'), table_name='candidate_pool')
    op.drop_table('candidate_pool')
    # ### end Alembic commands ###
