"""Add AI chat models

Revision ID: cf133f15dbd2
Revises: b5e77475fa20
Create Date: 2026-04-11 17:41:37.156837

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf133f15dbd2'
down_revision: Union[str, None] = 'b5e77475fa20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_sessions',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Auto-generated or user-defined conversation title'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_id'), 'ai_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_is_deleted'), 'ai_chat_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_public_id'), 'ai_chat_sessions', ['public_id'], unique=True)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='OpenAI-compatible role: user | assistant | system'),
    sa.Column('content', sa.Text(), nullable=False, comment='Raw text content of the message'),
    sa.Column('tokens', sa.Integer(), nullable=True, comment='Token count for this single message'),
    sa.Column('task_log_id', sa.Integer(), nullable=True, comment="If this message triggered an agentic task (tool use), it's linked here."),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_log_id'], ['ai_task_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_id'), 'ai_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_is_deleted'), 'ai_chat_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_task_log_id'), 'ai_chat_messages', ['task_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chat_messages_task_log_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_is_deleted'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_public_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_is_deleted'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_id'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    # ### end Alembic commands ###
