"""add_dsr_tables

Revision ID: 134885e270b6
Revises: 59e71c3daafb
Create Date: 2026-03-03 22:16:12.844826

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134885e270b6'
down_revision: Union[str, None] = '59e71c3daafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if ENUM types already exist (to prevent DuplicateObjectError)
    bind = op.get_bind()
    
    # Check dsrstatus
    res = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'dsrstatus'")).fetchone()
    if not res:
        sa.Enum('draft', 'submitted', 'approved', 'rejected', name='dsrstatus').create(bind)
        
    # Check dsractivitystatus
    res = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'dsractivitystatus'")).fetchone()
    if not res:
        sa.Enum('planned', 'in_progress', 'completed', 'on_hold', 'cancelled', name='dsractivitystatus').create(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsr_entries',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', name='dsrstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_previous_day_submission', sa.Boolean(), nullable=False, comment='True when report_date is before today'),
    sa.Column('previous_day_permission_granted_by', sa.Integer(), nullable=True, comment='Admin user who granted past-day submission permission'),
    sa.Column('items', sa.JSON(), nullable=False, comment='Array of work log items: project, activity, description, start_time, end_time, hours'),
    sa.Column('others', sa.JSON(), nullable=True, comment='Extensible metadata, reminder logs, etc.'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['previous_day_permission_granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_entries_id'), 'dsr_entries', ['id'], unique=False)
    op.create_index(op.f('ix_dsr_entries_is_deleted'), 'dsr_entries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dsr_entries_is_previous_day_submission'), 'dsr_entries', ['is_previous_day_submission'], unique=False)
    op.create_index(op.f('ix_dsr_entries_public_id'), 'dsr_entries', ['public_id'], unique=True)
    op.create_index(op.f('ix_dsr_entries_report_date'), 'dsr_entries', ['report_date'], unique=False)
    op.create_index(op.f('ix_dsr_entries_status'), 'dsr_entries', ['status'], unique=False)
    op.create_index(op.f('ix_dsr_entries_user_id'), 'dsr_entries', ['user_id'], unique=False)
    op.create_table('dsr_projects',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True, comment='Extensible project metadata (e.g. client, priority, tags)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_projects_id'), 'dsr_projects', ['id'], unique=False)
    op.create_index(op.f('ix_dsr_projects_is_active'), 'dsr_projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_dsr_projects_is_deleted'), 'dsr_projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dsr_projects_name'), 'dsr_projects', ['name'], unique=False)
    op.create_index(op.f('ix_dsr_projects_owner_id'), 'dsr_projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dsr_projects_public_id'), 'dsr_projects', ['public_id'], unique=True)
    op.create_table('dsr_activities',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'on_hold', 'cancelled', name='dsractivitystatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True, comment='Extensible metadata (e.g. priority, estimated_hours, labels)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['dsr_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_activities_id'), 'dsr_activities', ['id'], unique=False)
    op.create_index(op.f('ix_dsr_activities_is_active'), 'dsr_activities', ['is_active'], unique=False)
    op.create_index(op.f('ix_dsr_activities_is_deleted'), 'dsr_activities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dsr_activities_name'), 'dsr_activities', ['name'], unique=False)
    op.create_index(op.f('ix_dsr_activities_project_id'), 'dsr_activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_dsr_activities_public_id'), 'dsr_activities', ['public_id'], unique=True)
    op.create_index(op.f('ix_dsr_activities_status'), 'dsr_activities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsr_activities_status'), table_name='dsr_activities')
    op.drop_index(op.f('ix_dsr_activities_public_id'), table_name='dsr_activities')
    op.drop_index(op.f('ix_dsr_activities_project_id'), table_name='dsr_activities')
    op.drop_index(op.f('ix_dsr_activities_name'), table_name='dsr_activities')
    op.drop_index(op.f('ix_dsr_activities_is_deleted'), table_name='dsr_activities')
    op.drop_index(op.f('ix_dsr_activities_is_active'), table_name='dsr_activities')
    op.drop_index(op.f('ix_dsr_activities_id'), table_name='dsr_activities')
    op.drop_table('dsr_activities')
    op.drop_index(op.f('ix_dsr_projects_public_id'), table_name='dsr_projects')
    op.drop_index(op.f('ix_dsr_projects_owner_id'), table_name='dsr_projects')
    op.drop_index(op.f('ix_dsr_projects_name'), table_name='dsr_projects')
    op.drop_index(op.f('ix_dsr_projects_is_deleted'), table_name='dsr_projects')
    op.drop_index(op.f('ix_dsr_projects_is_active'), table_name='dsr_projects')
    op.drop_index(op.f('ix_dsr_projects_id'), table_name='dsr_projects')
    op.drop_table('dsr_projects')
    op.drop_index(op.f('ix_dsr_entries_user_id'), table_name='dsr_entries')
    op.drop_index(op.f('ix_dsr_entries_status'), table_name='dsr_entries')
    op.drop_index(op.f('ix_dsr_entries_report_date'), table_name='dsr_entries')
    op.drop_index(op.f('ix_dsr_entries_public_id'), table_name='dsr_entries')
    op.drop_index(op.f('ix_dsr_entries_is_previous_day_submission'), table_name='dsr_entries')
    op.drop_index(op.f('ix_dsr_entries_is_deleted'), table_name='dsr_entries')
    op.drop_index(op.f('ix_dsr_entries_id'), table_name='dsr_entries')
    op.drop_table('dsr_entries')
    # ### end Alembic commands ###
