"""update_training_assessment_fields

Revision ID: ce0a1441230d
Revises: 88455daeea6f
Create Date: 2026-01-10 15:11:28.359003

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0a1441230d'
down_revision: Union[str, None] = '88455daeea6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_assessments', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('training_assessments', sa.Column('course_name', sa.String(length=255), nullable=True))
    op.add_column('training_assessments', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.add_column('training_assessments', sa.Column('submission_date', sa.Date(), nullable=True))
    op.add_column('training_assessments', sa.Column('others', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_training_assessments_trainer_id'), 'training_assessments', ['trainer_id'], unique=False)
    op.create_foreign_key(None, 'training_assessments', 'users', ['trainer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_assessments', type_='foreignkey')
    op.drop_index(op.f('ix_training_assessments_trainer_id'), table_name='training_assessments')
    op.drop_column('training_assessments', 'others')
    op.drop_column('training_assessments', 'submission_date')
    op.drop_column('training_assessments', 'trainer_id')
    op.drop_column('training_assessments', 'course_name')
    op.drop_column('training_assessments', 'description')
    # ### end Alembic commands ###
