"""add leave to dsr

Revision ID: 2a674dc59b03
Revises: 0eae2b9c7bf3
Create Date: 2026-03-10 22:54:36.746488

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a674dc59b03'
down_revision: Union[str, None] = '0eae2b9c7bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsr_entries', sa.Column('is_leave', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('dsr_entries', sa.Column('leave_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_dsr_entries_is_leave'), 'dsr_entries', ['is_leave'], unique=False)
    op.create_index(op.f('ix_dsr_entries_leave_type'), 'dsr_entries', ['leave_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsr_entries_leave_type'), table_name='dsr_entries')
    op.drop_index(op.f('ix_dsr_entries_is_leave'), table_name='dsr_entries')
    op.drop_column('dsr_entries', 'leave_type')
    op.drop_column('dsr_entries', 'is_leave')
    # ### end Alembic commands ###
