"""add_dsr_project_requests

Revision ID: 1e7d5a6ac44a
Revises: edc35884e24e
Create Date: 2026-03-12 11:49:27.408060

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7d5a6ac44a'
down_revision: Union[str, None] = 'edc35884e24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsr_project_requests',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False, comment='Project name being requested'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Why this project needs to be added'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='dsrprojectrequeststatus'), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True, comment='Admin feedback on approval or rejection'),
    sa.Column('created_project_id', sa.Integer(), nullable=True, comment='Set to the newly created project ID when approved'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_project_id'], ['dsr_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_project_requests_id'), 'dsr_project_requests', ['id'], unique=False)
    op.create_index(op.f('ix_dsr_project_requests_is_deleted'), 'dsr_project_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dsr_project_requests_public_id'), 'dsr_project_requests', ['public_id'], unique=True)
    op.create_index(op.f('ix_dsr_project_requests_requested_by'), 'dsr_project_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_dsr_project_requests_status'), 'dsr_project_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsr_project_requests_status'), table_name='dsr_project_requests')
    op.drop_index(op.f('ix_dsr_project_requests_requested_by'), table_name='dsr_project_requests')
    op.drop_index(op.f('ix_dsr_project_requests_public_id'), table_name='dsr_project_requests')
    op.drop_index(op.f('ix_dsr_project_requests_is_deleted'), table_name='dsr_project_requests')
    op.drop_index(op.f('ix_dsr_project_requests_id'), table_name='dsr_project_requests')
    op.drop_table('dsr_project_requests')
    # ### end Alembic commands ###
