"""add_user_email_configuration_table

Revision ID: c61a61483442
Revises: ea1dab589341
Create Date: 2026-04-18 19:45:05.458171

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61a61483442'
down_revision: Union[str, None] = 'ea1dab589341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_configurations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('encryption', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email_configurations_id'), 'user_email_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_user_email_configurations_is_deleted'), 'user_email_configurations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_email_configurations_user_id'), 'user_email_configurations', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email_configurations_user_id'), table_name='user_email_configurations')
    op.drop_index(op.f('ix_user_email_configurations_is_deleted'), table_name='user_email_configurations')
    op.drop_index(op.f('ix_user_email_configurations_id'), table_name='user_email_configurations')
    op.drop_table('user_email_configurations')
    # ### end Alembic commands ###
